#!/usr/bin/env bash
# Gemini CLI Adapter — Generates GEMINI.md + .gemini/ from installed packs
# Usage: bash generate.sh <project-root>

set -euo pipefail

PROJECT_ROOT="${1:-.}"
NEXOS_LOCAL="$PROJECT_ROOT/.nexos"
PACKS_DIR="$NEXOS_LOCAL/packs"

mkdir -p "$PROJECT_ROOT/.gemini"

GEMINI_MD="$PROJECT_ROOT/GEMINI.md"

# ─── Generate GEMINI.md ─────────────────────────────────────────────────────

cat > "$GEMINI_MD" <<'HEADER'
# nexos Development Rules

> Auto-generated by nexos. Do not edit manually — run `nexos generate` to update.

## Agent System

Agents are activated with @agent-name syntax. Commands use the * prefix.
When an agent is active, read its definition from `.nexos/packs/<pack>/agents/<id>.md`.

### Maintenance Agents (nexos core)
- @skill-creator — Creates agents, tasks, and skills
- @squad-creator — Creates team compositions
- @pack-creator — Scaffolds new packs
- @schema-validator — Validates files against schemas

HEADER

# ─── Add pack content ───────────────────────────────────────────────────────

if [[ -d "$PACKS_DIR" ]]; then
  for pack_dir in "$PACKS_DIR"/*/; do
    [[ -d "$pack_dir" ]] || continue
    pname=$(basename "$pack_dir")
    [[ "$pname" == "_tmp_clone" ]] && continue

    echo "## Pack: $pname" >> "$GEMINI_MD"
    echo "" >> "$GEMINI_MD"

    # List agents
    if [[ -d "$pack_dir/agents" ]]; then
      echo "**Agents:**" >> "$GEMINI_MD"
      for agent_file in "$pack_dir"/agents/*.md; do
        [[ -f "$agent_file" ]] || continue
        aid=$(grep -m1 '^id:' "$agent_file" | sed 's/id: *//' | tr -d '"' | tr -d "'")
        atitle=$(grep -m1 '^title:' "$agent_file" | sed 's/title: *//' | tr -d '"' | tr -d "'")
        [[ -n "$aid" && -n "$atitle" ]] && echo "- @$aid — $atitle" >> "$GEMINI_MD"
      done
      echo "" >> "$GEMINI_MD"
    fi

    # Import rules via @file syntax
    if [[ -d "$pack_dir/rules" ]]; then
      echo "### Rules" >> "$GEMINI_MD"
      for rule_file in "$pack_dir"/rules/*.md; do
        [[ -f "$rule_file" ]] || continue
        # Use relative path from project root
        local_path="${rule_file#$PROJECT_ROOT/}"
        echo "@$local_path" >> "$GEMINI_MD"
      done
      echo "" >> "$GEMINI_MD"
    fi
  done
fi

# ─── Framework structure ────────────────────────────────────────────────────

cat >> "$GEMINI_MD" <<'FOOTER'
## Task Execution

When a command like `*develop` is invoked:
1. Read the task file from `.nexos/packs/<pack>/tasks/`
2. Follow the Steps section sequentially
3. Handle errors as described in Error Handling
4. Report results to the user
FOOTER

# ─── Generate settings.json ─────────────────────────────────────────────────

cat > "$PROJECT_ROOT/.gemini/settings.json" <<'SETTINGS'
{
  "context": {
    "fileName": ["AGENTS.md", "GEMINI.md"]
  }
}
SETTINGS

echo "[nexos] Generated: $GEMINI_MD"
echo "[nexos] Generated: $PROJECT_ROOT/.gemini/settings.json"
