#!/usr/bin/env bash
# Antigravity Adapter — Generates .agent/ files from installed packs
# Usage: bash generate.sh <project-root>

set -euo pipefail

PROJECT_ROOT="${1:-.}"
NEXOS_LOCAL="$PROJECT_ROOT/.nexos"
PACKS_DIR="$NEXOS_LOCAL/packs"

mkdir -p "$PROJECT_ROOT/.agent/rules" "$PROJECT_ROOT/.agent/skills" "$PROJECT_ROOT/.agent/workflows"

rules_content=""

# ─── Process packs ──────────────────────────────────────────────────────────

if [[ -d "$PACKS_DIR" ]]; then
  for pack_dir in "$PACKS_DIR"/*/; do
    [[ -d "$pack_dir" ]] || continue
    pname=$(basename "$pack_dir")
    [[ "$pname" == "_tmp_clone" ]] && continue

    # Merge rules into single rules.md
    if [[ -d "$pack_dir/rules" ]]; then
      for rule_file in "$pack_dir"/rules/*.md; do
        [[ -f "$rule_file" ]] || continue
        rules_content+="$(cat "$rule_file")"$'\n\n---\n\n'
      done
    fi

    # Create a skill per agent
    if [[ -d "$pack_dir/agents" ]]; then
      for agent_file in "$pack_dir"/agents/*.md; do
        [[ -f "$agent_file" ]] || continue
        aid=$(grep -m1 '^id:' "$agent_file" | sed 's/id: *//' | tr -d '"' | tr -d "'")
        if [[ -n "$aid" ]]; then
          mkdir -p "$PROJECT_ROOT/.agent/skills/$aid"
          cp "$agent_file" "$PROJECT_ROOT/.agent/skills/$aid/SKILL.md"
        fi
      done
    fi

    # Copy workflows
    if [[ -d "$pack_dir/workflows" ]]; then
      for wf_file in "$pack_dir"/workflows/*.yaml; do
        [[ -f "$wf_file" ]] || continue
        wf_base=$(basename "$wf_file" .yaml)
        cp "$wf_file" "$PROJECT_ROOT/.agent/workflows/$wf_base.md"
      done
    fi
  done
fi

# ─── Write merged rules ────────────────────────────────────────────────────

if [[ -n "$rules_content" ]]; then
  cat > "$PROJECT_ROOT/.agent/rules/rules.md" <<HEADER
# nexos Rules

> Auto-generated by nexos. Do not edit manually — run \`nexos generate\` to update.

$rules_content
HEADER
fi

echo "[nexos] Generated: $PROJECT_ROOT/.agent/rules/rules.md"
echo "[nexos] Generated: $PROJECT_ROOT/.agent/skills/*"
echo "[nexos] Generated: $PROJECT_ROOT/.agent/workflows/*"
